---
- name: Testing andrewrothstein.elasticsearch
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'elasticsearch --version'
      ansible.builtin.command: sh -lc 'elasticsearch --version'
      register: elasticsearch_test_output
      changed_when: false
    - name: Output from 'elasticsearch --version'
      ansible.builtin.debug:
        msg: '{{ elasticsearch_test_output.stdout }}'
