---
- name: (Debian) deps...
  apt: name={{item}} state=latest
  with_items:
    - openjdk-7-jre
    - openjdk-7-jdk

- name: (Debian) downloading deb...
  get_url: >-
    url={{elasticsearch_deb_url}}
    dest=/tmp/{{elasticsearch_deb}}

- name: (Debian) installing...
  apt: deb=/tmp/{{elasticsearch_deb}}
  