---
- name: download pkg
  become: yes
  become_user: root
  get_url: >-
    url={{elasticsearch_pkg_url}}
    dest=/tmp/{{elasticsearch_pkg}}
    mode=0644

- name: install deb
  when: ansible_os_family == 'Debian'
  become: '{{elasticsearch_privilege_escalate|default(True)}}'
  become_user: root
  apt: deb=/tmp/{{elasticsearch_pkg}} state=present
    
- name: install rpm
  become: '{{elasticsearch_privilege_escalate|default(True)}}'
  become_user: root
  when: ansible_os_family == 'RedHat'
  package: name=/tmp/{{elasticsearch_pkg}} state=present

