---
- name: resolve platform specific vars
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"

- name: download pkg
  become: yes
  become_user: root
  get_url: >-
    url={{elasticsearch_pkg_url}}
    dest=/tmp/{{elasticsearch_pkg}}
    mode=0644

- name: install deb
  when: ansible_os_family == 'Debian'
  become: yes
  become_user: root
  apt: deb=/tmp/{{elasticsearch_pkg}} state=present
    
- name: install rpm
  become: yes
  become_user: root
  when: ansible_os_family == 'RedHat'
  package: name=/tmp/{{elasticsearch_pkg}} state=present

- name: start elasticsearch
  service: name=elasticsearch state=started enabled=yes
